import './globals.css'
import type { Metadata } from 'next'
import { Inter, Roboto} from 'next/font/google'
import localFont from 'next/font/local'
import NavBar from './NavBar'
import {SessionProvider} from 'next-auth/react'
import AuthProvider from './auth/Provider'
import Script from 'next/script'
import GoogleAnalyticsScript from './GoogleAnalyticsScript'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap', // 添加这一行
  variable: '--font-inter' // 使用 CSS 变量
})

const robot =  Roboto({
  subsets: ['latin'],
  weight: ['400','500'],
})

const outfitFont = localFont({
  src: '../public/fonts/Outfit-VariableFont_wght.ttf'
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript/>
      <body className={outfitFont.className}>
        <AuthProvider>
        <NavBar />
        <main className='p-5'>{children}</main>
        </AuthProvider>
      </body>
    </html>
  )
}
